/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChannelRouteImport } from './routes/_authenticated/channel'
import { Route as AuthenticatedAutopilotRouteImport } from './routes/_authenticated/autopilot'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube/callback'
import { Route as ApiPublicSchedulerWorkerRouteImport } from './routes/api/public/scheduler/worker'
import { Route as ApiPublicAutopilotUploadRouteImport } from './routes/api/public/autopilot/upload'
import { Route as ApiPublicAutopilotTickRouteImport } from './routes/api/public/autopilot/tick'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelRoute = AuthenticatedChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutopilotRoute = AuthenticatedAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSchedulerWorkerRoute =
  ApiPublicSchedulerWorkerRouteImport.update({
    id: '/api/public/scheduler/worker',
    path: '/api/public/scheduler/worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutopilotUploadRoute =
  ApiPublicAutopilotUploadRouteImport.update({
    id: '/api/public/autopilot/upload',
    path: '/api/public/autopilot/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutopilotTickRoute = ApiPublicAutopilotTickRouteImport.update({
  id: '/api/public/autopilot/tick',
  path: '/api/public/autopilot/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/channel': typeof AuthenticatedChannelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/channel': typeof AuthenticatedChannelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/_authenticated/autopilot': typeof AuthenticatedAutopilotRoute
  '/_authenticated/channel': typeof AuthenticatedChannelRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unlock'
    | '/autopilot'
    | '/channel'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/schedule'
    | '/settings'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unlock'
    | '/autopilot'
    | '/channel'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/schedule'
    | '/settings'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unlock'
    | '/_authenticated/autopilot'
    | '/_authenticated/channel'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/library'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnlockRoute: typeof UnlockRoute
  ApiPublicAutopilotTickRoute: typeof ApiPublicAutopilotTickRoute
  ApiPublicAutopilotUploadRoute: typeof ApiPublicAutopilotUploadRoute
  ApiPublicSchedulerWorkerRoute: typeof ApiPublicSchedulerWorkerRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel': {
      id: '/_authenticated/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof AuthenticatedChannelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autopilot': {
      id: '/_authenticated/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AuthenticatedAutopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduler/worker': {
      id: '/api/public/scheduler/worker'
      path: '/api/public/scheduler/worker'
      fullPath: '/api/public/scheduler/worker'
      preLoaderRoute: typeof ApiPublicSchedulerWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/upload': {
      id: '/api/public/autopilot/upload'
      path: '/api/public/autopilot/upload'
      fullPath: '/api/public/autopilot/upload'
      preLoaderRoute: typeof ApiPublicAutopilotUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/tick': {
      id: '/api/public/autopilot/tick'
      path: '/api/public/autopilot/tick'
      fullPath: '/api/public/autopilot/tick'
      preLoaderRoute: typeof ApiPublicAutopilotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutopilotRoute: typeof AuthenticatedAutopilotRoute
  AuthenticatedChannelRoute: typeof AuthenticatedChannelRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutopilotRoute: AuthenticatedAutopilotRoute,
  AuthenticatedChannelRoute: AuthenticatedChannelRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnlockRoute: UnlockRoute,
  ApiPublicAutopilotTickRoute: ApiPublicAutopilotTickRoute,
  ApiPublicAutopilotUploadRoute: ApiPublicAutopilotUploadRoute,
  ApiPublicSchedulerWorkerRoute: ApiPublicSchedulerWorkerRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
