/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSplitRouteImport } from './routes/_authenticated/split'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChannelRouteImport } from './routes/_authenticated/channel'
import { Route as AuthenticatedAutopilotRouteImport } from './routes/_authenticated/autopilot'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube/callback'
import { Route as ApiPublicSplitterUpscaleTickRouteImport } from './routes/api/public/splitter/upscale-tick'
import { Route as ApiPublicSplitterUpscaleProgressRouteImport } from './routes/api/public/splitter/upscale-progress'
import { Route as ApiPublicSplitterUpscaleCompleteRouteImport } from './routes/api/public/splitter/upscale-complete'
import { Route as ApiPublicSplitterTickRouteImport } from './routes/api/public/splitter/tick'
import { Route as ApiPublicSplitterPrepareClipUploadRouteImport } from './routes/api/public/splitter/prepare-clip-upload'
import { Route as ApiPublicSplitterFinishRouteImport } from './routes/api/public/splitter/finish'
import { Route as ApiPublicSplitterCompleteRouteImport } from './routes/api/public/splitter/complete'
import { Route as ApiPublicSchedulerWorkerRouteImport } from './routes/api/public/scheduler/worker'
import { Route as ApiPublicAutopilotUploadRouteImport } from './routes/api/public/autopilot/upload'
import { Route as ApiPublicAutopilotTickRouteImport } from './routes/api/public/autopilot/tick'
import { Route as ApiPublicAutopilotRunWorkflowRouteImport } from './routes/api/public/autopilot/run-workflow'
import { Route as ApiPublicAutopilotHeartbeatRouteImport } from './routes/api/public/autopilot/heartbeat'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplitRoute = AuthenticatedSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelRoute = AuthenticatedChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutopilotRoute = AuthenticatedAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSplitterUpscaleTickRoute =
  ApiPublicSplitterUpscaleTickRouteImport.update({
    id: '/api/public/splitter/upscale-tick',
    path: '/api/public/splitter/upscale-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSplitterUpscaleProgressRoute =
  ApiPublicSplitterUpscaleProgressRouteImport.update({
    id: '/api/public/splitter/upscale-progress',
    path: '/api/public/splitter/upscale-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSplitterUpscaleCompleteRoute =
  ApiPublicSplitterUpscaleCompleteRouteImport.update({
    id: '/api/public/splitter/upscale-complete',
    path: '/api/public/splitter/upscale-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSplitterTickRoute = ApiPublicSplitterTickRouteImport.update({
  id: '/api/public/splitter/tick',
  path: '/api/public/splitter/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplitterPrepareClipUploadRoute =
  ApiPublicSplitterPrepareClipUploadRouteImport.update({
    id: '/api/public/splitter/prepare-clip-upload',
    path: '/api/public/splitter/prepare-clip-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSplitterFinishRoute = ApiPublicSplitterFinishRouteImport.update({
  id: '/api/public/splitter/finish',
  path: '/api/public/splitter/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplitterCompleteRoute =
  ApiPublicSplitterCompleteRouteImport.update({
    id: '/api/public/splitter/complete',
    path: '/api/public/splitter/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSchedulerWorkerRoute =
  ApiPublicSchedulerWorkerRouteImport.update({
    id: '/api/public/scheduler/worker',
    path: '/api/public/scheduler/worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutopilotUploadRoute =
  ApiPublicAutopilotUploadRouteImport.update({
    id: '/api/public/autopilot/upload',
    path: '/api/public/autopilot/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutopilotTickRoute = ApiPublicAutopilotTickRouteImport.update({
  id: '/api/public/autopilot/tick',
  path: '/api/public/autopilot/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutopilotRunWorkflowRoute =
  ApiPublicAutopilotRunWorkflowRouteImport.update({
    id: '/api/public/autopilot/run-workflow',
    path: '/api/public/autopilot/run-workflow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutopilotHeartbeatRoute =
  ApiPublicAutopilotHeartbeatRouteImport.update({
    id: '/api/public/autopilot/heartbeat',
    path: '/api/public/autopilot/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/channel': typeof AuthenticatedChannelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/split': typeof AuthenticatedSplitRoute
  '/api/public/autopilot/heartbeat': typeof ApiPublicAutopilotHeartbeatRoute
  '/api/public/autopilot/run-workflow': typeof ApiPublicAutopilotRunWorkflowRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/splitter/complete': typeof ApiPublicSplitterCompleteRoute
  '/api/public/splitter/finish': typeof ApiPublicSplitterFinishRoute
  '/api/public/splitter/prepare-clip-upload': typeof ApiPublicSplitterPrepareClipUploadRoute
  '/api/public/splitter/tick': typeof ApiPublicSplitterTickRoute
  '/api/public/splitter/upscale-complete': typeof ApiPublicSplitterUpscaleCompleteRoute
  '/api/public/splitter/upscale-progress': typeof ApiPublicSplitterUpscaleProgressRoute
  '/api/public/splitter/upscale-tick': typeof ApiPublicSplitterUpscaleTickRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/channel': typeof AuthenticatedChannelRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/split': typeof AuthenticatedSplitRoute
  '/api/public/autopilot/heartbeat': typeof ApiPublicAutopilotHeartbeatRoute
  '/api/public/autopilot/run-workflow': typeof ApiPublicAutopilotRunWorkflowRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/splitter/complete': typeof ApiPublicSplitterCompleteRoute
  '/api/public/splitter/finish': typeof ApiPublicSplitterFinishRoute
  '/api/public/splitter/prepare-clip-upload': typeof ApiPublicSplitterPrepareClipUploadRoute
  '/api/public/splitter/tick': typeof ApiPublicSplitterTickRoute
  '/api/public/splitter/upscale-complete': typeof ApiPublicSplitterUpscaleCompleteRoute
  '/api/public/splitter/upscale-progress': typeof ApiPublicSplitterUpscaleProgressRoute
  '/api/public/splitter/upscale-tick': typeof ApiPublicSplitterUpscaleTickRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unlock': typeof UnlockRoute
  '/_authenticated/autopilot': typeof AuthenticatedAutopilotRoute
  '/_authenticated/channel': typeof AuthenticatedChannelRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/split': typeof AuthenticatedSplitRoute
  '/api/public/autopilot/heartbeat': typeof ApiPublicAutopilotHeartbeatRoute
  '/api/public/autopilot/run-workflow': typeof ApiPublicAutopilotRunWorkflowRoute
  '/api/public/autopilot/tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/autopilot/upload': typeof ApiPublicAutopilotUploadRoute
  '/api/public/scheduler/worker': typeof ApiPublicSchedulerWorkerRoute
  '/api/public/splitter/complete': typeof ApiPublicSplitterCompleteRoute
  '/api/public/splitter/finish': typeof ApiPublicSplitterFinishRoute
  '/api/public/splitter/prepare-clip-upload': typeof ApiPublicSplitterPrepareClipUploadRoute
  '/api/public/splitter/tick': typeof ApiPublicSplitterTickRoute
  '/api/public/splitter/upscale-complete': typeof ApiPublicSplitterUpscaleCompleteRoute
  '/api/public/splitter/upscale-progress': typeof ApiPublicSplitterUpscaleProgressRoute
  '/api/public/splitter/upscale-tick': typeof ApiPublicSplitterUpscaleTickRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unlock'
    | '/autopilot'
    | '/channel'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/schedule'
    | '/settings'
    | '/split'
    | '/api/public/autopilot/heartbeat'
    | '/api/public/autopilot/run-workflow'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/splitter/complete'
    | '/api/public/splitter/finish'
    | '/api/public/splitter/prepare-clip-upload'
    | '/api/public/splitter/tick'
    | '/api/public/splitter/upscale-complete'
    | '/api/public/splitter/upscale-progress'
    | '/api/public/splitter/upscale-tick'
    | '/api/public/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unlock'
    | '/autopilot'
    | '/channel'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/schedule'
    | '/settings'
    | '/split'
    | '/api/public/autopilot/heartbeat'
    | '/api/public/autopilot/run-workflow'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/splitter/complete'
    | '/api/public/splitter/finish'
    | '/api/public/splitter/prepare-clip-upload'
    | '/api/public/splitter/tick'
    | '/api/public/splitter/upscale-complete'
    | '/api/public/splitter/upscale-progress'
    | '/api/public/splitter/upscale-tick'
    | '/api/public/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unlock'
    | '/_authenticated/autopilot'
    | '/_authenticated/channel'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/library'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/split'
    | '/api/public/autopilot/heartbeat'
    | '/api/public/autopilot/run-workflow'
    | '/api/public/autopilot/tick'
    | '/api/public/autopilot/upload'
    | '/api/public/scheduler/worker'
    | '/api/public/splitter/complete'
    | '/api/public/splitter/finish'
    | '/api/public/splitter/prepare-clip-upload'
    | '/api/public/splitter/tick'
    | '/api/public/splitter/upscale-complete'
    | '/api/public/splitter/upscale-progress'
    | '/api/public/splitter/upscale-tick'
    | '/api/public/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnlockRoute: typeof UnlockRoute
  ApiPublicAutopilotHeartbeatRoute: typeof ApiPublicAutopilotHeartbeatRoute
  ApiPublicAutopilotRunWorkflowRoute: typeof ApiPublicAutopilotRunWorkflowRoute
  ApiPublicAutopilotTickRoute: typeof ApiPublicAutopilotTickRoute
  ApiPublicAutopilotUploadRoute: typeof ApiPublicAutopilotUploadRoute
  ApiPublicSchedulerWorkerRoute: typeof ApiPublicSchedulerWorkerRoute
  ApiPublicSplitterCompleteRoute: typeof ApiPublicSplitterCompleteRoute
  ApiPublicSplitterFinishRoute: typeof ApiPublicSplitterFinishRoute
  ApiPublicSplitterPrepareClipUploadRoute: typeof ApiPublicSplitterPrepareClipUploadRoute
  ApiPublicSplitterTickRoute: typeof ApiPublicSplitterTickRoute
  ApiPublicSplitterUpscaleCompleteRoute: typeof ApiPublicSplitterUpscaleCompleteRoute
  ApiPublicSplitterUpscaleProgressRoute: typeof ApiPublicSplitterUpscaleProgressRoute
  ApiPublicSplitterUpscaleTickRoute: typeof ApiPublicSplitterUpscaleTickRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/split': {
      id: '/_authenticated/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof AuthenticatedSplitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel': {
      id: '/_authenticated/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof AuthenticatedChannelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autopilot': {
      id: '/_authenticated/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AuthenticatedAutopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/upscale-tick': {
      id: '/api/public/splitter/upscale-tick'
      path: '/api/public/splitter/upscale-tick'
      fullPath: '/api/public/splitter/upscale-tick'
      preLoaderRoute: typeof ApiPublicSplitterUpscaleTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/upscale-progress': {
      id: '/api/public/splitter/upscale-progress'
      path: '/api/public/splitter/upscale-progress'
      fullPath: '/api/public/splitter/upscale-progress'
      preLoaderRoute: typeof ApiPublicSplitterUpscaleProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/upscale-complete': {
      id: '/api/public/splitter/upscale-complete'
      path: '/api/public/splitter/upscale-complete'
      fullPath: '/api/public/splitter/upscale-complete'
      preLoaderRoute: typeof ApiPublicSplitterUpscaleCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/tick': {
      id: '/api/public/splitter/tick'
      path: '/api/public/splitter/tick'
      fullPath: '/api/public/splitter/tick'
      preLoaderRoute: typeof ApiPublicSplitterTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/prepare-clip-upload': {
      id: '/api/public/splitter/prepare-clip-upload'
      path: '/api/public/splitter/prepare-clip-upload'
      fullPath: '/api/public/splitter/prepare-clip-upload'
      preLoaderRoute: typeof ApiPublicSplitterPrepareClipUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/finish': {
      id: '/api/public/splitter/finish'
      path: '/api/public/splitter/finish'
      fullPath: '/api/public/splitter/finish'
      preLoaderRoute: typeof ApiPublicSplitterFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/splitter/complete': {
      id: '/api/public/splitter/complete'
      path: '/api/public/splitter/complete'
      fullPath: '/api/public/splitter/complete'
      preLoaderRoute: typeof ApiPublicSplitterCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduler/worker': {
      id: '/api/public/scheduler/worker'
      path: '/api/public/scheduler/worker'
      fullPath: '/api/public/scheduler/worker'
      preLoaderRoute: typeof ApiPublicSchedulerWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/upload': {
      id: '/api/public/autopilot/upload'
      path: '/api/public/autopilot/upload'
      fullPath: '/api/public/autopilot/upload'
      preLoaderRoute: typeof ApiPublicAutopilotUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/tick': {
      id: '/api/public/autopilot/tick'
      path: '/api/public/autopilot/tick'
      fullPath: '/api/public/autopilot/tick'
      preLoaderRoute: typeof ApiPublicAutopilotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/run-workflow': {
      id: '/api/public/autopilot/run-workflow'
      path: '/api/public/autopilot/run-workflow'
      fullPath: '/api/public/autopilot/run-workflow'
      preLoaderRoute: typeof ApiPublicAutopilotRunWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot/heartbeat': {
      id: '/api/public/autopilot/heartbeat'
      path: '/api/public/autopilot/heartbeat'
      fullPath: '/api/public/autopilot/heartbeat'
      preLoaderRoute: typeof ApiPublicAutopilotHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutopilotRoute: typeof AuthenticatedAutopilotRoute
  AuthenticatedChannelRoute: typeof AuthenticatedChannelRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSplitRoute: typeof AuthenticatedSplitRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutopilotRoute: AuthenticatedAutopilotRoute,
  AuthenticatedChannelRoute: AuthenticatedChannelRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSplitRoute: AuthenticatedSplitRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnlockRoute: UnlockRoute,
  ApiPublicAutopilotHeartbeatRoute: ApiPublicAutopilotHeartbeatRoute,
  ApiPublicAutopilotRunWorkflowRoute: ApiPublicAutopilotRunWorkflowRoute,
  ApiPublicAutopilotTickRoute: ApiPublicAutopilotTickRoute,
  ApiPublicAutopilotUploadRoute: ApiPublicAutopilotUploadRoute,
  ApiPublicSchedulerWorkerRoute: ApiPublicSchedulerWorkerRoute,
  ApiPublicSplitterCompleteRoute: ApiPublicSplitterCompleteRoute,
  ApiPublicSplitterFinishRoute: ApiPublicSplitterFinishRoute,
  ApiPublicSplitterPrepareClipUploadRoute:
    ApiPublicSplitterPrepareClipUploadRoute,
  ApiPublicSplitterTickRoute: ApiPublicSplitterTickRoute,
  ApiPublicSplitterUpscaleCompleteRoute: ApiPublicSplitterUpscaleCompleteRoute,
  ApiPublicSplitterUpscaleProgressRoute: ApiPublicSplitterUpscaleProgressRoute,
  ApiPublicSplitterUpscaleTickRoute: ApiPublicSplitterUpscaleTickRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
